"use client";
import type { AnchorHTMLAttributes } from "react";
import { useMemo, useState } from "react";
import BrandSignature from "../../BrandSignature";

const Link = ({ href, ...props }: AnchorHTMLAttributes<HTMLAnchorElement>) => <a href={href} {...props} />;

type Industry="natura"|"bistro"|"dom";
type Row={id:string;name:string;detail:string;stage:number;value:number;time:string};
const configs={
  natura:{brand:"Natura Studio",label:"KALENDARZ I OBSŁUGA STUDIA",title:"Wizyty, klienci i obłożenie bez chaosu.",stages:["Zapytanie","Potwierdzona","Przypomnienie","Wizyta","Płatność"],kpi:["Dzisiejsze wizyty","Obłożenie","Przychód dnia","Powroty klientów"],initial:[{id:"NS-214",name:"Marta K.",detail:"Rytuał twarzy",stage:3,value:280,time:"10:00"},{id:"NS-215",name:"Anna P.",detail:"Masaż relaksacyjny",stage:2,value:220,time:"12:30"},{id:"NS-216",name:"Katarzyna L.",detail:"Konsultacja",stage:1,value:120,time:"15:00"}],automation:"Po rezerwacji system potwierdza termin, dzień wcześniej wysyła przypomnienie, a po wizycie prośbę o opinię."},
  bistro:{brand:"Bistro Forma",label:"REZERWACJE I OPERACJE BISTRO",title:"Sala, rezerwacje i zamówienia w jednym rytmie.",stages:["Rezerwacja","Potwierdzona","Stolik gotowy","Goście","Rozliczona"],kpi:["Rezerwacje dziś","Zajęte stoliki","Średni rachunek","Obłożenie wieczoru"],initial:[{id:"BF-42",name:"Stolik 04",detail:"4 osoby · Kowalski",stage:3,value:286,time:"18:00"},{id:"BF-43",name:"Stolik 08",detail:"2 osoby · Nowak",stage:2,value:174,time:"19:00"},{id:"BF-44",name:"Stolik 02",detail:"6 osób · firma",stage:1,value:480,time:"20:00"}],automation:"Formularz rezerwacji sprawdza miejsce, wysyła potwierdzenie, tworzy zadanie przygotowania stolika i aktualizuje prognozę obłożenia."},
  dom:{brand:"Dom Dobry",label:"SPRZEDAŻ NIERUCHOMOŚCI",title:"Od zapytania o lokal do podpisania umowy.",stages:["Nowy lead","Kontakt","Prezentacja","Rezerwacja","Umowa"],kpi:["Nowe zapytania","Prezentacje","Zarezerwowane","Wartość pipeline"],initial:[{id:"DD-081",name:"Lokal A.12",detail:"Anna i Piotr · 68 m²",stage:3,value:720000,time:"czw. 16:00"},{id:"DD-082",name:"Lokal B.04",detail:"Marek W. · 54 m²",stage:2,value:586000,time:"pt. 12:00"},{id:"DD-083",name:"Lokal C.09",detail:"Joanna K. · 74 m²",stage:1,value:810000,time:"pon. 10:30"}],automation:"Zapytanie przypisuje doradcę, rezerwuje prezentację, pilnuje dokumentów, aktualizuje dostępność lokalu i przypomina o kolejnym kontakcie."},
} as const;

export default function IndustryDemo({industry}:{industry:Industry}){const c=configs[industry];const [rows,setRows]=useState<Row[]>(c.initial.map(x=>({...x})));const [events,setEvents]=useState([c.automation,"Dashboard KPI został przeliczony","Lista zadań zespołu jest aktualna"]);const stats=useMemo(()=>[rows.length,`${Math.round(rows.reduce((s,x)=>s+x.stage,0)/(rows.length*(c.stages.length-1))*100)}%`,`${rows.reduce((s,x)=>s+x.value,0).toLocaleString("pl-PL")} zł`,rows.filter(x=>x.stage>=3).length],[rows,c.stages.length]);
function advance(id:string){const row=rows.find(x=>x.id===id);if(!row)return;const next=Math.min(c.stages.length-1,row.stage+1);setRows(v=>v.map(x=>x.id===id?{...x,stage:next}:x));setEvents(v=>[`${id}: ${c.stages[next]}. Wykonano następne zadania procesu`,...v].slice(0,5))}
function add(){const id=`${industry.toUpperCase().slice(0,2)}-${300+rows.length}`;setRows(v=>[...v,{id,name:industry==="bistro"?"Nowy stolik":industry==="dom"?"Nowy klient":"Nowa rezerwacja",detail:"Dane z formularza strony",stage:0,value:industry==="dom"?640000:200,time:"nowe"}]);setEvents(v=>[`${id}: formularz utworzył rekord i powiadomił zespół`,...v].slice(0,5))}
return <main className={`industry-demo industry-${industry}`}><header><Link className="brand" href="/"><BrandSignature compact /></Link><span className="demo-badge">DEMO PROCESOWE · DANE PRZYKŁADOWE</span><Link href="/#kontakt">Zapytaj o takie zaplecze ↗</Link></header><div className="industry-shell"><section className="industry-title"><div><span className="section-no">{c.brand.toUpperCase()} / {c.label}</span><h1>{c.title}</h1><p>Interaktywny przykład tego, co właściciel i zespół mogą widzieć po zalogowaniu.</p></div><button onClick={add}>+ Zasymuluj dane z formularza</button></section><section className="transport-kpis">{c.kpi.map((name,index)=><article key={name}><span>{name}</span><b>{stats[index]}</b><small>wartość demonstracyjna</small></article>)}</section><section className="industry-grid"><div className="transport-card"><div className="transport-head"><div><span className="section-no">BIEŻĄCA PRACA</span><h2>{industry==="bistro"?"Sala i rezerwacje":industry==="dom"?"Klienci i lokale":"Kalendarz wizyt"}</h2></div><small>Zmień etap i obserwuj automat</small></div>{rows.map(row=><article className="industry-row" key={row.id}><div><b>{row.time}</b><small>{row.id}</small></div><div><strong>{row.name}</strong><small>{row.detail}</small></div><span>{c.stages[row.stage]}</span><div><i style={{width:`${(row.stage+1)/c.stages.length*100}%`}}/></div><button disabled={row.stage===c.stages.length-1} onClick={()=>advance(row.id)}>{row.stage===c.stages.length-1?"Gotowe":"Następny etap →"}</button></article>)}</div><aside className="transport-card"><div className="transport-head"><div><span className="section-no">AUTOMATYZACJE</span><h2>Dziennik działania</h2></div></div><div className="automation-log">{events.map((event,index)=><p key={`${event}-${index}`}><i/> {event}</p>)}</div><div className="automation-note"><b>Pełna wersja wdrożeniowa</b><span>Role użytkowników, prawdziwa baza danych, integracje, kopie, eksporty, instrukcja i testy QA. Zakres zawsze dobierany jest do realnego procesu firmy.</span></div></aside></section><section className="process-blueprint"><div><span className="section-no">MAPA PROCESU</span><h2>Od wejścia klienta do wyniku i KPI.</h2></div><div>{c.stages.map((stage,index)=><article key={stage}><b>{String(index+1).padStart(2,"0")}</b><span>{stage}</span>{index<c.stages.length-1&&<i>→</i>}</article>)}</div></section></div></main>}
