export const services = [
  { title: "ZM Start", price: "od 2 490 zł netto", lead: "Jedna konkretna strona prowadząca lokalnego klienta z Google do telefonu lub zapytania.", forWhom: "Lokalne usługi potrzebujące prostej, profesjonalnej obecności online.", includes: ["One Page do ok. 7 sekcji", "telefon, WhatsApp, mapa i formularz", "lokalne SEO i spójne dane firmy", "podłączenie domeny lub hostingu klienta", "testy, publikacja i 14 dni wsparcia"], time: "zwykle 7 dni roboczych" },
  { title: "ZM LeadFlow", price: "od 4 490 zł netto", lead: "Strona i formularz kwalifikujący, które zamieniają ogólne pytania w kompletne zgłoszenia.", forWhom: "Warsztaty, wykonawcy, instalatorzy, serwisy i inne firmy wyceniające zlecenia.", includes: ["do 6 podstron", "indywidualny układ i treści", "formularz z terminem i zdjęciami", "lokalne SEO i mierzenie zapytań", "publikacja, QA i 14 dni wsparcia"], time: "zwykle 10–14 dni roboczych" },
  { title: "ZM Flow AI", price: "od 6 900 zł netto", lead: "Strona, formularz i chatbot połączone z prostym obiegiem zapytań.", forWhom: "Firmy, które otrzymują wiele powtarzalnych pytań i chcą szybciej kwalifikować klientów.", includes: ["strona i formularz kwalifikujący", "chatbot FAQ lub AI z zatwierdzoną bazą wiedzy", "przekazanie kontaktu człowiekowi", "analityka i testy", "możliwość dalszej automatyzacji"], time: "zwykle 14–21 dni roboczych" },
  { title: "Sklep internetowy Start", price: "5 499–8 499 zł", lead: "Prosty sklep z jasną ścieżką od produktu do bezpiecznego zamówienia.", forWhom: "Małe marki rozpoczynające sprzedaż do około 20 produktów bez nietypowych integracji magazynowych.", includes: ["WooCommerce lub Shopify i do 20 produktów", "koszyk, płatności i podstawowe formy dostawy", "widok mobilny i e-maile transakcyjne", "instrukcja obsługi zamówień", "testy zakupowe, bezpieczeństwa i kontrola jakości"], time: "zwykle 4–6 tygodni" },
  { title: "Automatyzacja Start", price: "1 200–2 500 zł", lead: "Jedna powtarzalna czynność przestaje być wykonywana ręcznie.", forWhom: "Firmy przepisujące zapytania, wysyłające te same wiadomości lub pilnujące terminów w pamięci.", includes: ["krótka analiza procesu", "jeden przepływ automatyczny", "formularz, status lub powiadomienie", "instrukcja obsługi", "scenariusze awaryjne i kontrola jakości"], time: "około 1–2 tygodni" },
  { title: "Najważniejsze liczby firmy", price: "1 800–3 500 zł", lead: "Sprzedaż, koszty i terminy na jednym czytelnym ekranie, bez szukania po arkuszach.", forWhom: "Właściciele, którzy chcą widzieć sprzedaż, koszty, terminy, zlecenia i skuteczność.", includes: ["5–8 uzgodnionych wskaźników (KPI)", "dane z 1–2 źródeł", "pulpit z wynikami na telefon i komputer", "filtry i okresy", "sprawdzenie danych i kontrola jakości"], time: "około 1–3 tygodni" },
  { title: "Cyfrowy obieg zleceń", price: "3 500–7 500 zł", lead: "Od zapytania klienta do realizacji, dokumentów i raportu, ze statusami i mniejszą liczbą pomyłek.", forWhom: "Transport, serwis, montaże, ekipy terenowe i firmy pracujące na wielu zleceniach.", includes: ["formularz i baza zleceń", "etapy, terminy i odpowiedzialność", "powiadomienia i dokumenty", "pulpit z najważniejszymi liczbami (KPI)", "szkolenie i kontrola jakości procesu"], time: "około 3–6 tygodni" },
  { title: "Panel klienta", price: "4 900–8 900 zł", lead: "Klient sam sprawdza etap projektu, terminy i dokumenty, bez kolejnych telefonów o status.", forWhom: "Firmy realizujące dłuższe projekty, zamówienia lub usługi etapowe.", includes: ["bezpieczny indywidualny kod", "postęp, etapy i następny krok", "umowy i dokumenty", "widok mobilny", "testy dostępu, bezpieczeństwa i kontrola jakości"], time: "około 4–7 tygodni" },
  { title: "Teksty na stronę i wizytówkę", price: "od 350 zł", lead: "Zamieniam wiedzę o Twojej firmie w prosty język, który klient rozumie i który prowadzi do kontaktu.", forWhom: "Firmy, które mają doświadczenie i ofertę, ale nie chcą pisać tekstów od zera.", includes: ["wizytówka Google: opis firmy, usługi i FAQ, od 350 zł", "landing page: nagłówki, 5–7 sekcji i CTA, od 650 zł", "strona firmowa do 7 podstron, od 1 500 zł", "opisy usług lub realizacji, od 120 zł za stronę", "jedna tura korekt po Twoich uwagach"], time: "około 3–10 dni, zależnie od zakresu" },
  { title: "Audyt procesu firmy", price: "900–1 500 zł", lead: "Najpierw ustalamy, gdzie firma traci czas i które usprawnienie naprawdę się opłaci.", forWhom: "Firmy, które czują chaos, ale nie wiedzą jeszcze, od czego zacząć.", includes: ["rozmowa i mapa procesu", "wąskie gardła", "lista możliwych automatyzacji", "priorytety i orientacyjne koszty", "plan dalszego wdrożenia"], time: "około 3–5 dni" },
  { title: "Opieka nad stroną", price: "249–490 zł / mies.", lead: "Strona pozostaje aktualna, bezpieczna i sprawdzana także po publikacji.", forWhom: "Małe firmy, które chcą mieć jedną osobę do bieżącej opieki zamiast samodzielnie pilnować technicznych spraw.", includes: ["monitoring dostępności, SSL i podstawowych błędów", "kontrolowane aktualizacje systemu, motywu i dodatków", "kopie bezpieczeństwa oraz sprawdzenie możliwości odtworzenia", "do 60 minut drobnych zmian treści miesięcznie w wyższym wariancie", "kontrola formularza i kluczowych ścieżek", "krótkie miesięczne podsumowanie i reakcja na zgłoszenia w dni robocze"], time: "abonament miesięczny; zakres i czas reakcji ustalane przed startem" },
];

export const technologies = [
  { title: "Samodzielna edycja strony", tools: "WordPress, PHP, edytor blokowy, WooCommerce", summary: "Strona, którą możesz samodzielnie aktualizować.", what: "WordPress to prosty panel do zarządzania treścią. PHP to język, na którym działa część jego zaplecza. Po zalogowaniu zmieniasz teksty, zdjęcia, ofertę lub realizacje bez dotykania kodu.", use: "Strony firmowe, blogi, portfolio i proste sklepy.", effect: "Niezależność od wykonawcy przy codziennych zmianach." },
  { title: "Strona szyta na miarę", tools: "React, Next.js, TypeScript", summary: "Szybkie, indywidualne strony i aplikacje.", what: "React i Next.js to technologie do budowy nowoczesnych widoków, kalkulatorów, paneli i nietypowych funkcji, których nie daje gotowy szablon.", use: "Serwisy premium, panele klienta, portale i narzędzia firmowe.", effect: "Duża szybkość, elastyczność i możliwość dalszej rozbudowy." },
  { title: "Automatyzacje", tools: "n8n, Make, Power Automate, webhooki", summary: "System wykonuje powtarzalne kroki za pracownika.", what: "Łączymy formularze, e-mail, arkusze i systemy tak, aby dane przepływały między nimi bez ręcznego kopiowania.", use: "Zapytania, przypomnienia, oferty, statusy, raporty i dokumenty.", effect: "Mniej pomyłek i więcej czasu na właściwą pracę." },
  { title: "Wyniki firmy na jednym ekranie", tools: "dashboard WWW, Looker Studio, Power BI", summary: "Najważniejsze wyniki na jednym ekranie.", what: "Czytelny pulpit pokazujący uzgodnione wskaźniki (KPI), np. sprzedaż, marżę, terminowość, liczbę zapytań i obciążenie zespołu.", use: "Codzienne decyzje właściciela i raportowanie wyników.", effect: "Szybciej widzisz problem i reagujesz na podstawie danych." },
  { title: "Excel i Google Sheets", tools: "Excel, Google Sheets, formularze", summary: "Dane uporządkowane bez kupowania dużego systemu.", what: "Kalkulatory, rejestry, wyceny i raporty z formułami, walidacją i automatycznymi podsumowaniami.", use: "Pierwszy krok przed CRM lub dedykowaną aplikacją.", effect: "Jedna wersja danych i mniej ręcznych obliczeń." },
  { title: "Baza klientów i zapytań", tools: "lekki CRM, D1, Airtable lub wybrane API", summary: "Kontakty, szanse i kolejne działania w jednym miejscu.", what: "CRM to prosta baza klientów. Porządkujemy w niej klientów, historię rozmów, wartość ofert i terminy dalszego kontaktu.", use: "Sprzedaż usług, obsługa zapytań i powracający klienci.", effect: "Żadne zapytanie nie ginie, a sprzedaż ma wyraźny następny krok." },
  { title: "Panel dla klienta", tools: "aplikacja WWW, bezpieczny kod, PWA", summary: "Klient widzi etap, termin i dokumenty bez telefonu.", what: "Prywatny, mobilny widok projektu lub zlecenia. Może działać jak aplikacja dodana do ekranu telefonu (PWA).", use: "Projekty etapowe, transport, serwis, budownictwo i zamówienia.", effect: "Mniej pytań o status i bardziej profesjonalna obsługa." },
  { title: "Łączenie używanych narzędzi", tools: "API, webhooki, poczta, kalendarz", summary: "Różne narzędzia zaczynają ze sobą współpracować.", what: "API i webhooki to bezpieczne sposoby przekazywania danych. Łączymy nimi stronę, arkusz, bazę klientów, kalendarz lub system zamówień.", use: "Gdy firma posiada już kilka narzędzi i powtarza dane w każdym z nich.", effect: "Spójne informacje i krótszy obieg pracy." },
  { title: "AI i dokumenty", tools: "AI, OCR, klasyfikacja, szablony", summary: "Pomoc przy odczytywaniu i porządkowaniu informacji.", what: "System może wyciągać dane z dokumentów, przygotować robocze podsumowanie lub przypisać wiadomość do odpowiedniej kategorii.", use: "Dokumenty transportowe, zapytania, notatki i baza wiedzy.", effect: "Szybsze przygotowanie pracy, zawsze z kontrolą człowieka." },
  { title: "Google i SEO lokalne", tools: "Profil Firmy Google, Search Console, Analytics", summary: "Firma jest łatwiejsza do znalezienia i kontaktu.", what: "Porządkujemy informacje, usługi, zdjęcia, opis i spójność danych firmy oraz łączymy wizytówkę z dobrze przygotowaną stroną.", use: "Firmy działające lokalnie i zdobywające klientów z Map Google.", effect: "Lepsza widoczność i możliwość mierzenia telefonów oraz zapytań, bez gwarantowania pozycji." },
  { title: "Podstawy nowoczesnego WWW", tools: "HTML, CSS, JavaScript, TypeScript", summary: "To konstrukcja, wygląd i interakcje każdej dobrej strony.", what: "HTML porządkuje treść, CSS odpowiada za wygląd, JavaScript za działanie, a TypeScript pomaga ograniczać błędy w większych projektach.", use: "Każda strona, formularz, kalkulator i panel internetowy.", effect: "Czytelna, responsywna i łatwiejsza do utrzymania strona." },
  { title: "Bazy danych i zaplecze", tools: "SQL, Cloudflare D1, bezpieczne API", summary: "Informacje firmy są zapisywane i dostępne tam, gdzie są potrzebne.", what: "Baza przechowuje zapytania, klientów, zlecenia, statusy i dokumenty. Zaplecze kontroluje, kto może je odczytać lub zmienić.", use: "CRM, panel klienta, portfolio, rejestr zleceń i dashboard KPI.", effect: "Jedno źródło danych zamiast wielu niespójnych plików." },
  { title: "Hosting, GitHub i bezpieczeństwo", tools: "Cloudflare Workers, Git, GitHub, HTTPS", summary: "Strona jest publikowana, zabezpieczona i gotowa do dalszego rozwoju.", what: "GitHub przechowuje historię kodu, Cloudflare uruchamia stronę, a HTTPS szyfruje połączenie. Dobieramy też kopie, monitoring i zasady aktualizacji.", use: "Publikacja, współpraca, przywracanie wersji i bezpieczne utrzymanie.", effect: "Stabilne działanie oraz mniejsze ryzyko utraty zmian." },
];

export const concepts = {
  "natura-studio": { name: "Natura Studio", category: "Wellness i uroda", accent: "#9bb8a4", headline: "Spokojna marka, która prowadzi prosto do rezerwacji.", challenge: "Połączyć delikatny charakter marki z prostą ścieżką wyboru zabiegu i kontaktu.", solution: "Lekka strona usługowa z cennikiem, opisami zabiegów, opiniami jako przyszłym modułem i mocnym przyciskiem rezerwacji.", stack: ["WordPress lub React", "SEO lokalne", "formularz rezerwacji"], image: "/concept-natura.jpg", website: "/demo/natura-strona", demo: "/demo/natura" },
  "bistro-forma": { name: "Bistro Forma", category: "Gastronomia", accent: "#c89059", headline: "Menu, klimat i rezerwacja bez szukania informacji.", challenge: "Pokazać charakter miejsca i najważniejsze informacje w pierwszych sekundach.", solution: "Mobilna strona z aktualnym menu, godzinami, mapą, rezerwacją stolika i miejscem na wydarzenia.", stack: ["React", "Profil Firmy Google", "menu i analityka"], image: "/concept-bistro.jpg", website: "/demo/bistro-strona", demo: "/demo/bistro" },
  "dom-dobry": { name: "Dom Dobry", category: "Nieruchomości", accent: "#8ca5b3", headline: "Oferta nieruchomości przedstawiona jasno i wiarygodnie.", challenge: "Uporządkować inwestycje, standard i dostępność lokali tak, aby klient szybko przeszedł do rozmowy.", solution: "Katalog inwestycji z filtrami, kartą lokalu, formularzem oraz panelem do aktualizacji statusów.", stack: ["Next.js", "panel oferty", "formularz i CRM"], image: "/concept-dom.jpg", website: "/demo/dom-strona", demo: "/demo/dom" },
} as const;
